# Generated by Django 5.0.14 on 2026-01-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skills_person_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
        ),
    ]
